version: '3.9'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: ./app
    environment:
      DATABASE_URL: "mysql+asyncmy://todo_user:todo_pass@db:3306/todo_db"
    depends_on:
      db:
        condition: service_healthy
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build: ./frontend
    container_name: todo-frontend
    expose:
      - "8080"

  nginx:
    build: ./nginx
    container_name: todo-nginx
    ports:
      - "80:80"
    depends_on:
      - app
      - frontend 